Config as an option
restorando/samson-cli pull request #2
Opened 2017-12-01 14:35 UTC by Pato94

## Rationale
I'm trying to use samson-cli to deploy multiple projects, periodically. For this purpose I've set up a cron that makes use of this tool. I've found two different problems so far.

- I need a different config file for each project I want to deploy. This is kind of a waste, since the only thing that differs from file to file is the project name
- I can't specify a custom location for the config file.

For our particular use-case the approach that fits better is to specify the config via options

## Implementation
- Program modules no longer do `require('../config')` and instead receive a parameter called `config`
- Tab completion module enable deploys completion only if the `samsonrc.json` file is present

2017-12-01 14:48 UTC, jfresco requested changes
Nice one! Can you update `README.md` telling how to use the `config` parameter?

2017-12-01 15:04 UTC, Pato94 commented
♻️

2017-12-01 15:16 UTC, jfresco approved these changes
:shipit:

2017-12-01 15:21 UTC, merged

2017-12-05 14:52 UTC, klaus993 commented
👏